### ISSUE TITLE
Compilation Fails on MinGW

### ISSUE THREAD

**Issue by mrjackv** [esseks/monicelli#28] opened 2015-10-22 22:06 UTC
While I was trying to compile monicelli in MinGW I got the following errors:
### 1. Boost native() assumes std::string is made of wchar_t under windows

```
main.cpp:112:81: error: conversion from 'const string_type {aka const std::__cxx11::basic_string<wchar_t>}' to non-scalar type 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}' requested
```

I think it's not a mistake on monicelli's part (I think boost assumes that all string are wchar in windows), however judging from the boost documentation string() would be a more fitting option, e.g.

```
std::string outputname = boost::filesystem::path(name).filename().string();
```
### 2. CppEmitter fuctions expect bool return and instead get ostream

```
CppEmitter.cpp: In member function 'virtual bool monicelli::CppEmitter::emit(const monicelli::Program&)':
CppEmitter.cpp:78:12: error: cannot convert 'std::ostream {aka std::basic_ostream<char>}' to 'bool' in return
return stream;
       ^
```

(a.k.a. #27)
I'm unsure whether it's an unimplemented feature of the GCC I'm using or some linux-only autoconversion. According to [this example](http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool) the typecast should be explicit. 
#### Build Details

The following packages were used to compile:
[Mingw x86/64 sjlj with pthreads](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.1.0/threads-posix/sjlj/x86_64-5.1.0-release-posix-sjlj-rt_v4-rev0.7z)
[msys2-provided flex](http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/flex-2.5.39-4-x86_64.pkg.tar.xz)
[msys2-provided bison](http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/bison-3.0.4-1-x86_64.pkg.tar.xz)
As for the rest:
- Boost 1.59
- LLVM 3.6
- Yaml-cpp ( jbeder/yaml-cpp@03d6e7d67271be698d9a2fd51f749201649e0223 )

They've been compiled from source with the respective checkouts/tars
The cmake (3.2.2) was run with the following command

```
cmake .. -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/monicelli -DCMAKE_BUILD_TYPE=RELEASE -DBOOST_INCLUDEDIR=/opt/boost/include/boost-1_59 -DBOOST_LIBRARYDIR=/opt/boost/lib -DLLVM_DIR=/opt/llvm/share/llvm/cmake -DYAML_INCLUDE_DIRS=/opt/yaml-cpp/include -DYAML_LIBRARIES=/opt/yaml-cpp/lib/libyaml-cpp.a -DCMAKE_CXX_FLAGS="-I/usr/include"
```

P.S. Kudos for the awesome language

**Comment by esseks** [comment] 2015-10-24 11:41
Hi, thanks for the detailed report.

Regarding point 1, I will try to fix it asap. Expect a commit shortly. If you could confirm that things work as intended it would be great!

Regarding point 2, the `explicit` part in the `explicit operator bool() const` signature is meant to replace the safe-bool idiom we used to use before C++11, it doesn't mean you have to write `bool(stream)`. I admit the name could be misleading, though. Essentially, since `bool` can be converted from/to `int`, without the `explicit` or the safe-bool idiom the following nonsense would compile:

     int i = stream << 4;

but without a `bool` cast we couldn't write things like:

    if (stream >> x) {
        // do stuff
    }

It looks like the MinGW compiler hasn't catched up yet with this C++11 feature. I should think about the best way to solve the issue.

**Comment by esseks** [comment] 2015-10-24 11:45
Hi, thanks for the detailed report.

Regarding point 1, I will try to fix it asap. Expect a commit shortly. If you could confirm that things work as intended it would be great!

Regarding point 2, the `explicit` part in the `explicit operator bool() const` signature is meant to replace the safe-bool idiom we used to use before C++11. It doesn't mean you have to write `bool(stream)`, although I admit the name could be misleading. Essentially, since `bool` can be converted from/to `int`, without the `explicit` or the safe-bool idiom the following nonsense would compile:

     int i = stream << 4;

but without a `bool` cast we couldn't write things like:

    if (stream >> x) {
        // do stuff
    }

Could it be that the MinGW compiler hasn't catched up yet with this C++11 feature? I will investigate.

**Comment by esseks** [comment] 2015-12-15 16:42
Apologies for the very long time the bugfix is taking, unfortunately I am yet to find the time to setup a windows build environment with all the required components.

**Comment by esseks** [comment] 2019-06-24 09:18
This issue should be solved in the latest release. I'm closing this issue as obsolete, but feel free to reopen it if it doesn't work for you.

**Closed by esseks** 2019-06-24 09:18 UTC
Labels: bug
